// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTrbBbN56-IuG-wGe-qa2eZrRYFaSxei4',
    appId: '1:626596124525:android:825e024273ce05de27ec64',
    messagingSenderId: '626596124525',
    projectId: 'saidco-657c5',
    databaseURL: 'https://saidco-657c5-default-rtdb.firebaseio.com',
    storageBucket: 'saidco-657c5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgSYQOUiG-aNMJvxLgo0OQsNbNOsIG5Xc',
    appId: '1:626596124525:ios:79cebf31dc010baf27ec64',
    messagingSenderId: '626596124525',
    projectId: 'saidco-657c5',
    databaseURL: 'https://saidco-657c5-default-rtdb.firebaseio.com',
    storageBucket: 'saidco-657c5.firebasestorage.app',
    iosBundleId: 'com.example.saidco',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKuFBsbMysgLs7j0AIMnJUgifDjSYlDfg',
    appId: '1:626596124525:web:d75d42b1351f871527ec64',
    messagingSenderId: '626596124525',
    projectId: 'saidco-657c5',
    authDomain: 'saidco-657c5.firebaseapp.com',
    databaseURL: 'https://saidco-657c5-default-rtdb.firebaseio.com',
    storageBucket: 'saidco-657c5.firebasestorage.app',
    measurementId: 'G-5JRP48DTRQ',
  );
}
